'use strict';
S.title='Kariyama Research / Layout Library';
const example={status:'テンプレート見本',source:'Kariyama Research · レイアウト見本。図と数値は実験結果ではない。',notes:'layouts.js の対応する S.add(...) を複製して編集する。本文30px、見出し44pxを基本とする。内容が多い場合は別ページかノートへ移す。'};
S.add('研究・開発報告',`<div class="cover-grid"><div class="cover-copy"><p class="cover-kicker">RESEARCH / DEVELOPMENT</p><h2>研究・開発報告<br>HTMLスライドテンプレート</h2><p class="subtitle">設計・実装・評価を、図とともに説明する</p><p class="author">刈山 湊<br>2026.09.07</p></div><div class="cover-side"><div class="cover-line"></div><div class="cover-mark">KARIYAMA<small>RESEARCH SLIDES</small></div><div class="cover-palette" aria-label="Navy、Blue、Cyan、Mint、Redの配色"><i style="--color:var(--brand-ink)"></i><i style="--color:var(--brand-blue)"></i><i style="--color:var(--brand-cyan)"></i><i style="--color:var(--brand-mint)"></i><i style="--color:var(--brand-red)"></i></div><p class="caption">Navy / Blue / Mint<br>16:9 · Offline HTML</p></div></div>`,{...example,kind:'cover',layout:'cover',notes:'表紙は参考資料の左右2:1の構成を継承。所属は自分の発表先に合わせて追記。右側は自分のロゴまたは主図に置き換えられる。'});
S.add('概要',`<ul class="bullets"><li><strong>課題</strong><br>何を解決するか、対象と条件を示す</li><li><strong>工夫点</strong><br>入力・アーキテクチャ・評価方法の差分を示す</li><li><strong>結果と次の作業</strong><br>分かったことと、まだ確認できていないことを分ける</li></ul>`+S.take('1ページにつき、主に伝える内容は1つ'),{...example,layout:'overview'});
S.add('工夫点',`<div class="section-copy"><div class="section-index">02</div><div class="stack"><h2>アーキテクチャと学習</h2><p class="lead">入力表現から、目的関数まで</p></div></div>`+S.take('設計 → 実装 → 検証の順に説明する'),{...example,kind:'section',layout:'section'});
S.add('アーキテクチャ',`<p class="lead">入力・共有表現・出力の対応を示す</p>`+S.fig('assets/architecture.svg','構成図の見本。実際のモジュール名・shape・接続に置き換える。')+S.annotation('差分となるモジュールを強調する',false),{...example,layout:'architecture'});
S.add('工夫点と元論文の図',S.split(`<div class="paper-placeholder"><div><b>原論文の Fig. を配置</b><p>縦横比を保ち、図中文字が読める大きさにする</p><p class="caption">ここは画像差し替え用の枠です</p></div></div><p class="caption">著者名, 論文名, 年, Fig.番号 / DOI・URL</p>`,`<h2>図から説明すること</h2><ul class="bullets small"><li>入力と出力</li><li>既存手法との違い</li><li>今回採用する部分</li></ul>`+S.annotation('原図と自分の拡張を区別する'), 'figure-first'),{...example,layout:'paper-figure',notes:'他者の論文図はテンプレートへ同梱していない。利用する原図の出典と権利を確認して差し替える。拡張部分は独自図として分ける。'});
S.add('既存構成と変更点',S.split(`<h2 class="compare-head">既存構成</h2>`+S.flow([['入力','固定した特徴'],['推定','タスク別モデル']],{compact:true})+`<ul class="bullets small"><li>前提条件</li><li>現状の制約</li></ul>`,`<h2 class="compare-head proposed">変更後の構成</h2>`+S.flow([['入力','表現の見直し'],['推定','共有表現','mint']],{compact:true})+`<ul class="bullets small"><li>追加した工夫</li><li>新たに検証する項目</li></ul>`)+S.take('変更箇所以外の条件を固定して比較する'),{...example,layout:'comparison'});
S.add('入力表現とマスク',`<div class="token-caption"><span>入力トークン</span><span>12要素の配置見本</span></div>`+S.tokens()+`<div class="token-caption"><span>観測する要素 / マスクする要素</span><span>× は未観測</span></div>`+S.tokens([1,4,7,10])+S.flow([['Tokenize','要素をベクトルに変換'],['Encoder','観測した要素で推論'],['Objective','対象との対応を学習','mint']],{compact:true})+S.take('入力の軸・単位・マスク単位を明記する'),{...example,layout:'tokenization'});
S.add('損失設計',`<div class="formula"><span class="math">L</span> = <span class="math">L</span><sub>task</sub> + λ<sub>1</sub><span class="math">L</span><sub>masked</sub> + λ<sub>2</sub><span class="math">L</span><sub>contrastive</sub></div>`+S.split(`<h2>各項の役割</h2><dl class="equation-key"><dt>L<sub>task</sub></dt><dd>タスクの教師信号</dd><dt>L<sub>masked</sub></dt><dd>未観測部分の予測</dd><dt>L<sub>contrastive</sub></dt><dd>表現間の対応</dd></dl>`,`<h2>検証する内容</h2><ul class="bullets small"><li>各項を除いた場合との差</li><li>重み λ の選択方法</li><li>教師信号・負例の条件</li></ul>`)+S.take('数式は設計の見本。実際に使う項だけを残す'),{...example,layout:'equation'});
S.add('性能比較',S.bars(['条件 A','条件 B','条件 C'],[{name:'比較手法（見本）',color:'var(--comparison)',values:[62,55,48]},{name:'変更後（見本）',color:'var(--brand-blue)',values:[69,61,54]}],{title:'Accuracy（ダミーデータ）'})+S.take('評価分割・分母・seed・モデル選択方法を脚注に記載する'),{...example,layout:'results',source:'ダミーデータ · レイアウト確認用。実験・ベンチマークの結果ではない。'});
S.add('Ablation',S.table(['設定','項 A','項 B','指標 ↑','差分'],[['基準','なし','なし','62.0','—'],['変更 1','あり','なし','65.5','+3.5'],['変更 2','なし','あり','61.2','−0.8'],['変更 1 + 2','あり','あり','未測定','—']],{numeric:[3,4],highlight:1})+S.annotation('改善・悪化・未測定を、そのまま示す',false)+S.take('表の数値は見本。比較で固定した条件も記載する'),{...example,layout:'ablation',source:'ダミーデータ · 改善・悪化・未測定の表示例。'});
S.add('計測と前処理',S.flow([['取得','センサー・計測条件'],['品質確認','欠損・時刻・外れ値'],['前処理','変換・正規化'],['保存','入力・メタデータ','mint']])+S.table(['段階','確認する項目'],[['Firmware / 計測','取得レート・パケット形式・同期方法'],['前処理','窓長・変換順序・正規化のfit対象'],['データ管理','人物・環境・日付・評価分割']])+S.take('計測条件とモデル入力を、同じ図でつなぐ'),{...example,layout:'protocol'});
S.add('アプリ画面',S.fig('assets/monitor-example.png','SilentSense Monitor / 2026-09-06の記録画面。入力はMM-Fi再生、実機接続ではない。',{kind:'app',alt:'SilentSense Monitorの部屋、人体点群、信号グラフを含む記録画面'}),{...example,layout:'app',source:'自作アプリの記録画面 · platform/docs/monitor-person-restored.png · 2026-09-06',notes:'この画像は自作アプリの実画面。新しい資料では対象バージョンの画面に置き換え、撮影日・入力種別・実測か模式図かを添える。'});
S.add('画面の詳細',S.split(S.fig('assets/monitor-detail.png','Monitorの3D表示領域を切り出した例。'),`<h2>3D表示</h2><ul class="bullets small"><li>部屋は参照モデル</li><li>人体点群は姿勢由来</li><li>電波点群はCSI由来の描画</li></ul>`+S.annotation('何が実測で、何が派生表示かを示す'), 'figure-first'),{...example,layout:'detail',source:'自作アプリの記録画面から切り出し · 2026-09-06'});
S.add('実装の要点',S.split(`<pre class="code"><span class="comment"># 形状を明示する疑似コード</span>
tokens = tokenize(signal)
<span class="comment"># [B, T, C] → [B, N, D]</span>
latent = backbone(tokens)
prediction = head(latent)

loss = task_loss(prediction, target)
loss += weight * auxiliary_loss(latent)</pre>`,`<h2>確認する差分</h2><ul class="bullets small"><li>入力と出力のshape</li><li>追加した演算</li><li>学習時と推論時の違い</li></ul>`+S.annotation('等幅フォントはコード・データだけ',false))+S.take('長い実装はリポジトリへ。ここでは説明に必要な部分だけ示す'),{...example,layout:'implementation'});
S.add('評価条件',S.table(['項目','必ず記載する内容'],[['データセット','名称・版・対象subset・サンプル数'],['分割','人物・環境・時間の分離条件'],['学習','Optimizer・LR・epoch・seed'],['比較','同じ入力・分割・予算かどうか'],['評価','指標・単位・平均とばらつき']])+S.take('同条件でない結果は、直接比較と区別して示す'),{...example,layout:'evidence'});
S.add('配色と図形',`<div class="swatches">${[['Navy','#132c96'],['Blue','#0054b5'],['Cyan','#17aabd'],['Mint','#008579'],['Red','#ed3131']].map(([label,color])=>'<div class="swatch" style="--color:'+color+'"><i></i><b>'+label+'</b><code>'+color+'</code></div>').join('')}</div>`+S.flow([['基本の矩形','入力・処理・出力'],['強調する矩形','差分・評価','mint']])+S.annotation('短い注釈にはCyanの吹き出し',false)+S.take('色だけで意味を伝えず、ラベル・線・形も併用する'),{...example,layout:'palette'});
S.add('図を中心に説明する',S.fig('assets/token-groups.svg','要素の対応とグループ境界の見本。図全体を画像化せずSVGとして編集できる。')+S.take('変更する箇所を揃え、対応関係を図で追えるようにする'),{...example,layout:'figure'});
S.add('まとめ',`<div class="closing-rule"></div><h2>結論と、次に確認すること</h2><p class="lead">できたこと / 分かったこと / 未確認のこと</p><p class="small muted">資料名・日付・連絡先</p>`,{...example,layout:'closing',kind:'closing'});
